export const defaultBirthdayColumnVisibility = {
	enlistmentPeriod: false,
	isGraduated: false,
	major: false,
	phone: false,
	policyBeneficiaryGroup: false,
	politicalOrg: false,
	politicalOrgOfficialDate: false,
	cpvId: false,
	previousPosition: false,
	previousUnit: false,
	religion: false,
	schoolName: false,
	shortcoming: false,
	talent: false,
	fatherName: false,
	fatherJob: false,
	fatherPhoneNumber: false,
	motherName: false,
	motherJob: false,
	motherPhoneNumber: false,
	cpvOfficialAt: false,
	ethnic: false,
	educationLevel: false
}

export const defaultCpvOfficialColumnVisibility = {
	enlistmentPeriod: false,
	isGraduated: false,
	major: false,
	phone: false,
	position: false,
	policyBeneficiaryGroup: false,
	politicalOrg: false,
	politicalOrgOfficialDate: false,
	cpvId: false,
	previousPosition: false,
	religion: false,
	schoolName: false,
	shortcoming: false,
	talent: false,
	fatherName: false,
	fatherJob: false,
	fatherPhoneNumber: false,
	motherName: false,
	motherJob: false,
	motherPhoneNumber: false,
	dob: false,
	ethnic: false,
	educationLevel: false,
	rank: false
}
