DROP TABLE `classes`;--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_students` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` text DEFAULT CURRENT_TIMESTAMP,
	`fullName` text DEFAULT '',
	`birthPlace` text DEFAULT '',
	`address` text DEFAULT '',
	`dob` text DEFAULT '',
	`rank` text DEFAULT '',
	`previousUnit` text DEFAULT '',
	`previousPosition` text DEFAULT '',
	`position` text DEFAULT 'Chiến sĩ',
	`positionId` integer,
	`ethnic` text DEFAULT '',
	`religion` text DEFAULT 'Không',
	`enlistmentPeriod` text DEFAULT '',
	`politicalOrg` text NOT NULL,
	`politicalOrgOfficialDate` text DEFAULT '',
	`cpvId` text,
	`educationLevel` text DEFAULT '',
	`schoolName` text DEFAULT '',
	`major` text DEFAULT '',
	`isGraduated` integer DEFAULT false,
	`talent` text DEFAULT 'Không',
	`shortcoming` text DEFAULT 'Không',
	`policyBeneficiaryGroup` text DEFAULT 'Không',
	`fatherName` text DEFAULT '',
	`fatherDob` text DEFAULT '',
	`fatherPhoneNumber` text DEFAULT '',
	`fatherJob` text DEFAULT '',
	`motherName` text DEFAULT '',
	`motherDob` text DEFAULT '',
	`motherPhoneNumber` text DEFAULT '',
	`motherJob` text DEFAULT '',
	`isMarried` integer DEFAULT false,
	`spouseName` text DEFAULT '',
	`spouseDob` text DEFAULT '',
	`spouseJob` text DEFAULT '',
	`spousePhoneNumber` text DEFAULT '',
	`childrenInfos` text DEFAULT '[]',
	`familySize` integer,
	`familyBackground` text DEFAULT 'Không',
	`familyBirthOrder` text DEFAULT '',
	`achievement` text DEFAULT 'Không',
	`disciplinaryHistory` text DEFAULT 'Không',
	`phone` text DEFAULT '',
	`unitId` integer,
	`cpvOfficialAt` text,
	`avatar` text,
	`siblings` text DEFAULT '[]',
	`contactPerson` text DEFAULT '{}',
	`studentId` text,
	`relatedDocumentations` text,
	`status` text DEFAULT 'pending' NOT NULL,
	FOREIGN KEY (`positionId`) REFERENCES `positions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`unitId`) REFERENCES `units`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_students`("id", "createdAt", "updatedAt", "fullName", "birthPlace", "address", "dob", "rank", "previousUnit", "previousPosition", "position", "positionId", "ethnic", "religion", "enlistmentPeriod", "politicalOrg", "politicalOrgOfficialDate", "cpvId", "educationLevel", "schoolName", "major", "isGraduated", "talent", "shortcoming", "policyBeneficiaryGroup", "fatherName", "fatherDob", "fatherPhoneNumber", "fatherJob", "motherName", "motherDob", "motherPhoneNumber", "motherJob", "isMarried", "spouseName", "spouseDob", "spouseJob", "spousePhoneNumber", "childrenInfos", "familySize", "familyBackground", "familyBirthOrder", "achievement", "disciplinaryHistory", "phone", "unitId", "cpvOfficialAt", "avatar", "siblings", "contactPerson", "studentId", "relatedDocumentations", "status") SELECT "id", "createdAt", "updatedAt", "fullName", "birthPlace", "address", "dob", "rank", "previousUnit", "previousPosition", "position", "positionId", "ethnic", "religion", "enlistmentPeriod", "politicalOrg", "politicalOrgOfficialDate", "cpvId", "educationLevel", "schoolName", "major", "isGraduated", "talent", "shortcoming", "policyBeneficiaryGroup", "fatherName", "fatherDob", "fatherPhoneNumber", "fatherJob", "motherName", "motherDob", "motherPhoneNumber", "motherJob", "isMarried", "spouseName", "spouseDob", "spouseJob", "spousePhoneNumber", "childrenInfos", "familySize", "familyBackground", "familyBirthOrder", "achievement", "disciplinaryHistory", "phone", "unitId", "cpvOfficialAt", "avatar", "siblings", "contactPerson", "studentId", "relatedDocumentations", "status" FROM `students`;--> statement-breakpoint
DROP TABLE `students`;--> statement-breakpoint
ALTER TABLE `__new_students` RENAME TO `students`;--> statement-breakpoint
PRAGMA foreign_keys=ON;