/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaiTroRouteImport } from './routes/vai-tro'
import { Route as ThongKeDoanhTraiRouteImport } from './routes/thong-ke-doanh-trai'
import { Route as ThongKeChinhTriRouteImport } from './routes/thong-ke-chinh-tri'
import { Route as ReligionRouteImport } from './routes/religion'
import { Route as QuanLyDonViRouteImport } from './routes/quan-ly-don-vi'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListUserRouteImport } from './routes/list-user'
import { Route as KhoiTaoQtvRouteImport } from './routes/khoi-tao-qtv'
import { Route as KhoiTaoDonViRouteImport } from './routes/khoi-tao-don-vi'
import { Route as ImportStudentsRouteImport } from './routes/import-students'
import { Route as HoanCanhKhoKhanRouteImport } from './routes/hoan-canh-kho-khan'
import { Route as HcyuRouteImport } from './routes/hcyu'
import { Route as EthnicMinorityRouteImport } from './routes/ethnic-minority'
import { Route as CpvRouteImport } from './routes/cpv'
import { Route as ChuyenDangChinhThucRouteImport } from './routes/chuyen-dang-chinh-thuc'
import { Route as CacQuyenRouteImport } from './routes/cac-quyen'
import { Route as BirthdayRouteImport } from './routes/birthday'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrungDoiPlatoonAliasRouteImport } from './routes/trung-doi/$platoonAlias'
import { Route as TieuDoanAliasRouteImport } from './routes/tieu-doan/$alias'
import { Route as QuanLyVatTuDanhMucRouteImport } from './routes/quan-ly-vat-tu.danh-muc'
import { Route as DaiDoiCompanyAliasRouteImport } from './routes/dai-doi/$companyAlias'
import { Route as ClassesClassIdRouteImport } from './routes/classes/$classId'

const VaiTroRoute = VaiTroRouteImport.update({
  id: '/vai-tro',
  path: '/vai-tro',
  getParentRoute: () => rootRouteImport,
} as any)
const ThongKeDoanhTraiRoute = ThongKeDoanhTraiRouteImport.update({
  id: '/thong-ke-doanh-trai',
  path: '/thong-ke-doanh-trai',
  getParentRoute: () => rootRouteImport,
} as any)
const ThongKeChinhTriRoute = ThongKeChinhTriRouteImport.update({
  id: '/thong-ke-chinh-tri',
  path: '/thong-ke-chinh-tri',
  getParentRoute: () => rootRouteImport,
} as any)
const ReligionRoute = ReligionRouteImport.update({
  id: '/religion',
  path: '/religion',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyDonViRoute = QuanLyDonViRouteImport.update({
  id: '/quan-ly-don-vi',
  path: '/quan-ly-don-vi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListUserRoute = ListUserRouteImport.update({
  id: '/list-user',
  path: '/list-user',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoiTaoQtvRoute = KhoiTaoQtvRouteImport.update({
  id: '/khoi-tao-qtv',
  path: '/khoi-tao-qtv',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoiTaoDonViRoute = KhoiTaoDonViRouteImport.update({
  id: '/khoi-tao-don-vi',
  path: '/khoi-tao-don-vi',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportStudentsRoute = ImportStudentsRouteImport.update({
  id: '/import-students',
  path: '/import-students',
  getParentRoute: () => rootRouteImport,
} as any)
const HoanCanhKhoKhanRoute = HoanCanhKhoKhanRouteImport.update({
  id: '/hoan-canh-kho-khan',
  path: '/hoan-canh-kho-khan',
  getParentRoute: () => rootRouteImport,
} as any)
const HcyuRoute = HcyuRouteImport.update({
  id: '/hcyu',
  path: '/hcyu',
  getParentRoute: () => rootRouteImport,
} as any)
const EthnicMinorityRoute = EthnicMinorityRouteImport.update({
  id: '/ethnic-minority',
  path: '/ethnic-minority',
  getParentRoute: () => rootRouteImport,
} as any)
const CpvRoute = CpvRouteImport.update({
  id: '/cpv',
  path: '/cpv',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuyenDangChinhThucRoute = ChuyenDangChinhThucRouteImport.update({
  id: '/chuyen-dang-chinh-thuc',
  path: '/chuyen-dang-chinh-thuc',
  getParentRoute: () => rootRouteImport,
} as any)
const CacQuyenRoute = CacQuyenRouteImport.update({
  id: '/cac-quyen',
  path: '/cac-quyen',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayRoute = BirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrungDoiPlatoonAliasRoute = TrungDoiPlatoonAliasRouteImport.update({
  id: '/trung-doi/$platoonAlias',
  path: '/trung-doi/$platoonAlias',
  getParentRoute: () => rootRouteImport,
} as any)
const TieuDoanAliasRoute = TieuDoanAliasRouteImport.update({
  id: '/tieu-doan/$alias',
  path: '/tieu-doan/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyVatTuDanhMucRoute = QuanLyVatTuDanhMucRouteImport.update({
  id: '/quan-ly-vat-tu/danh-muc',
  path: '/quan-ly-vat-tu/danh-muc',
  getParentRoute: () => rootRouteImport,
} as any)
const DaiDoiCompanyAliasRoute = DaiDoiCompanyAliasRouteImport.update({
  id: '/dai-doi/$companyAlias',
  path: '/dai-doi/$companyAlias',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cac-quyen': typeof CacQuyenRoute
  '/chuyen-dang-chinh-thuc': typeof ChuyenDangChinhThucRoute
  '/cpv': typeof CpvRoute
  '/ethnic-minority': typeof EthnicMinorityRoute
  '/hcyu': typeof HcyuRoute
  '/hoan-canh-kho-khan': typeof HoanCanhKhoKhanRoute
  '/import-students': typeof ImportStudentsRoute
  '/khoi-tao-don-vi': typeof KhoiTaoDonViRoute
  '/khoi-tao-qtv': typeof KhoiTaoQtvRoute
  '/list-user': typeof ListUserRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quan-ly-don-vi': typeof QuanLyDonViRoute
  '/religion': typeof ReligionRoute
  '/thong-ke-chinh-tri': typeof ThongKeChinhTriRoute
  '/thong-ke-doanh-trai': typeof ThongKeDoanhTraiRoute
  '/vai-tro': typeof VaiTroRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/dai-doi/$companyAlias': typeof DaiDoiCompanyAliasRoute
  '/quan-ly-vat-tu/danh-muc': typeof QuanLyVatTuDanhMucRoute
  '/tieu-doan/$alias': typeof TieuDoanAliasRoute
  '/trung-doi/$platoonAlias': typeof TrungDoiPlatoonAliasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cac-quyen': typeof CacQuyenRoute
  '/chuyen-dang-chinh-thuc': typeof ChuyenDangChinhThucRoute
  '/cpv': typeof CpvRoute
  '/ethnic-minority': typeof EthnicMinorityRoute
  '/hcyu': typeof HcyuRoute
  '/hoan-canh-kho-khan': typeof HoanCanhKhoKhanRoute
  '/import-students': typeof ImportStudentsRoute
  '/khoi-tao-don-vi': typeof KhoiTaoDonViRoute
  '/khoi-tao-qtv': typeof KhoiTaoQtvRoute
  '/list-user': typeof ListUserRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quan-ly-don-vi': typeof QuanLyDonViRoute
  '/religion': typeof ReligionRoute
  '/thong-ke-chinh-tri': typeof ThongKeChinhTriRoute
  '/thong-ke-doanh-trai': typeof ThongKeDoanhTraiRoute
  '/vai-tro': typeof VaiTroRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/dai-doi/$companyAlias': typeof DaiDoiCompanyAliasRoute
  '/quan-ly-vat-tu/danh-muc': typeof QuanLyVatTuDanhMucRoute
  '/tieu-doan/$alias': typeof TieuDoanAliasRoute
  '/trung-doi/$platoonAlias': typeof TrungDoiPlatoonAliasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cac-quyen': typeof CacQuyenRoute
  '/chuyen-dang-chinh-thuc': typeof ChuyenDangChinhThucRoute
  '/cpv': typeof CpvRoute
  '/ethnic-minority': typeof EthnicMinorityRoute
  '/hcyu': typeof HcyuRoute
  '/hoan-canh-kho-khan': typeof HoanCanhKhoKhanRoute
  '/import-students': typeof ImportStudentsRoute
  '/khoi-tao-don-vi': typeof KhoiTaoDonViRoute
  '/khoi-tao-qtv': typeof KhoiTaoQtvRoute
  '/list-user': typeof ListUserRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quan-ly-don-vi': typeof QuanLyDonViRoute
  '/religion': typeof ReligionRoute
  '/thong-ke-chinh-tri': typeof ThongKeChinhTriRoute
  '/thong-ke-doanh-trai': typeof ThongKeDoanhTraiRoute
  '/vai-tro': typeof VaiTroRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/dai-doi/$companyAlias': typeof DaiDoiCompanyAliasRoute
  '/quan-ly-vat-tu/danh-muc': typeof QuanLyVatTuDanhMucRoute
  '/tieu-doan/$alias': typeof TieuDoanAliasRoute
  '/trung-doi/$platoonAlias': typeof TrungDoiPlatoonAliasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthday'
    | '/cac-quyen'
    | '/chuyen-dang-chinh-thuc'
    | '/cpv'
    | '/ethnic-minority'
    | '/hcyu'
    | '/hoan-canh-kho-khan'
    | '/import-students'
    | '/khoi-tao-don-vi'
    | '/khoi-tao-qtv'
    | '/list-user'
    | '/login'
    | '/profile'
    | '/quan-ly-don-vi'
    | '/religion'
    | '/thong-ke-chinh-tri'
    | '/thong-ke-doanh-trai'
    | '/vai-tro'
    | '/classes/$classId'
    | '/dai-doi/$companyAlias'
    | '/quan-ly-vat-tu/danh-muc'
    | '/tieu-doan/$alias'
    | '/trung-doi/$platoonAlias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthday'
    | '/cac-quyen'
    | '/chuyen-dang-chinh-thuc'
    | '/cpv'
    | '/ethnic-minority'
    | '/hcyu'
    | '/hoan-canh-kho-khan'
    | '/import-students'
    | '/khoi-tao-don-vi'
    | '/khoi-tao-qtv'
    | '/list-user'
    | '/login'
    | '/profile'
    | '/quan-ly-don-vi'
    | '/religion'
    | '/thong-ke-chinh-tri'
    | '/thong-ke-doanh-trai'
    | '/vai-tro'
    | '/classes/$classId'
    | '/dai-doi/$companyAlias'
    | '/quan-ly-vat-tu/danh-muc'
    | '/tieu-doan/$alias'
    | '/trung-doi/$platoonAlias'
  id:
    | '__root__'
    | '/'
    | '/birthday'
    | '/cac-quyen'
    | '/chuyen-dang-chinh-thuc'
    | '/cpv'
    | '/ethnic-minority'
    | '/hcyu'
    | '/hoan-canh-kho-khan'
    | '/import-students'
    | '/khoi-tao-don-vi'
    | '/khoi-tao-qtv'
    | '/list-user'
    | '/login'
    | '/profile'
    | '/quan-ly-don-vi'
    | '/religion'
    | '/thong-ke-chinh-tri'
    | '/thong-ke-doanh-trai'
    | '/vai-tro'
    | '/classes/$classId'
    | '/dai-doi/$companyAlias'
    | '/quan-ly-vat-tu/danh-muc'
    | '/tieu-doan/$alias'
    | '/trung-doi/$platoonAlias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdayRoute: typeof BirthdayRoute
  CacQuyenRoute: typeof CacQuyenRoute
  ChuyenDangChinhThucRoute: typeof ChuyenDangChinhThucRoute
  CpvRoute: typeof CpvRoute
  EthnicMinorityRoute: typeof EthnicMinorityRoute
  HcyuRoute: typeof HcyuRoute
  HoanCanhKhoKhanRoute: typeof HoanCanhKhoKhanRoute
  ImportStudentsRoute: typeof ImportStudentsRoute
  KhoiTaoDonViRoute: typeof KhoiTaoDonViRoute
  KhoiTaoQtvRoute: typeof KhoiTaoQtvRoute
  ListUserRoute: typeof ListUserRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuanLyDonViRoute: typeof QuanLyDonViRoute
  ReligionRoute: typeof ReligionRoute
  ThongKeChinhTriRoute: typeof ThongKeChinhTriRoute
  ThongKeDoanhTraiRoute: typeof ThongKeDoanhTraiRoute
  VaiTroRoute: typeof VaiTroRoute
  ClassesClassIdRoute: typeof ClassesClassIdRoute
  DaiDoiCompanyAliasRoute: typeof DaiDoiCompanyAliasRoute
  QuanLyVatTuDanhMucRoute: typeof QuanLyVatTuDanhMucRoute
  TieuDoanAliasRoute: typeof TieuDoanAliasRoute
  TrungDoiPlatoonAliasRoute: typeof TrungDoiPlatoonAliasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vai-tro': {
      id: '/vai-tro'
      path: '/vai-tro'
      fullPath: '/vai-tro'
      preLoaderRoute: typeof VaiTroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thong-ke-doanh-trai': {
      id: '/thong-ke-doanh-trai'
      path: '/thong-ke-doanh-trai'
      fullPath: '/thong-ke-doanh-trai'
      preLoaderRoute: typeof ThongKeDoanhTraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thong-ke-chinh-tri': {
      id: '/thong-ke-chinh-tri'
      path: '/thong-ke-chinh-tri'
      fullPath: '/thong-ke-chinh-tri'
      preLoaderRoute: typeof ThongKeChinhTriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/religion': {
      id: '/religion'
      path: '/religion'
      fullPath: '/religion'
      preLoaderRoute: typeof ReligionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-don-vi': {
      id: '/quan-ly-don-vi'
      path: '/quan-ly-don-vi'
      fullPath: '/quan-ly-don-vi'
      preLoaderRoute: typeof QuanLyDonViRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-user': {
      id: '/list-user'
      path: '/list-user'
      fullPath: '/list-user'
      preLoaderRoute: typeof ListUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoi-tao-qtv': {
      id: '/khoi-tao-qtv'
      path: '/khoi-tao-qtv'
      fullPath: '/khoi-tao-qtv'
      preLoaderRoute: typeof KhoiTaoQtvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoi-tao-don-vi': {
      id: '/khoi-tao-don-vi'
      path: '/khoi-tao-don-vi'
      fullPath: '/khoi-tao-don-vi'
      preLoaderRoute: typeof KhoiTaoDonViRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-students': {
      id: '/import-students'
      path: '/import-students'
      fullPath: '/import-students'
      preLoaderRoute: typeof ImportStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoan-canh-kho-khan': {
      id: '/hoan-canh-kho-khan'
      path: '/hoan-canh-kho-khan'
      fullPath: '/hoan-canh-kho-khan'
      preLoaderRoute: typeof HoanCanhKhoKhanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hcyu': {
      id: '/hcyu'
      path: '/hcyu'
      fullPath: '/hcyu'
      preLoaderRoute: typeof HcyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethnic-minority': {
      id: '/ethnic-minority'
      path: '/ethnic-minority'
      fullPath: '/ethnic-minority'
      preLoaderRoute: typeof EthnicMinorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpv': {
      id: '/cpv'
      path: '/cpv'
      fullPath: '/cpv'
      preLoaderRoute: typeof CpvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuyen-dang-chinh-thuc': {
      id: '/chuyen-dang-chinh-thuc'
      path: '/chuyen-dang-chinh-thuc'
      fullPath: '/chuyen-dang-chinh-thuc'
      preLoaderRoute: typeof ChuyenDangChinhThucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cac-quyen': {
      id: '/cac-quyen'
      path: '/cac-quyen'
      fullPath: '/cac-quyen'
      preLoaderRoute: typeof CacQuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday': {
      id: '/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof BirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trung-doi/$platoonAlias': {
      id: '/trung-doi/$platoonAlias'
      path: '/trung-doi/$platoonAlias'
      fullPath: '/trung-doi/$platoonAlias'
      preLoaderRoute: typeof TrungDoiPlatoonAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tieu-doan/$alias': {
      id: '/tieu-doan/$alias'
      path: '/tieu-doan/$alias'
      fullPath: '/tieu-doan/$alias'
      preLoaderRoute: typeof TieuDoanAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-vat-tu/danh-muc': {
      id: '/quan-ly-vat-tu/danh-muc'
      path: '/quan-ly-vat-tu/danh-muc'
      fullPath: '/quan-ly-vat-tu/danh-muc'
      preLoaderRoute: typeof QuanLyVatTuDanhMucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dai-doi/$companyAlias': {
      id: '/dai-doi/$companyAlias'
      path: '/dai-doi/$companyAlias'
      fullPath: '/dai-doi/$companyAlias'
      preLoaderRoute: typeof DaiDoiCompanyAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdayRoute: BirthdayRoute,
  CacQuyenRoute: CacQuyenRoute,
  ChuyenDangChinhThucRoute: ChuyenDangChinhThucRoute,
  CpvRoute: CpvRoute,
  EthnicMinorityRoute: EthnicMinorityRoute,
  HcyuRoute: HcyuRoute,
  HoanCanhKhoKhanRoute: HoanCanhKhoKhanRoute,
  ImportStudentsRoute: ImportStudentsRoute,
  KhoiTaoDonViRoute: KhoiTaoDonViRoute,
  KhoiTaoQtvRoute: KhoiTaoQtvRoute,
  ListUserRoute: ListUserRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuanLyDonViRoute: QuanLyDonViRoute,
  ReligionRoute: ReligionRoute,
  ThongKeChinhTriRoute: ThongKeChinhTriRoute,
  ThongKeDoanhTraiRoute: ThongKeDoanhTraiRoute,
  VaiTroRoute: VaiTroRoute,
  ClassesClassIdRoute: ClassesClassIdRoute,
  DaiDoiCompanyAliasRoute: DaiDoiCompanyAliasRoute,
  QuanLyVatTuDanhMucRoute: QuanLyVatTuDanhMucRoute,
  TieuDoanAliasRoute: TieuDoanAliasRoute,
  TrungDoiPlatoonAliasRoute: TrungDoiPlatoonAliasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
