// Code generated by the Encore v1.58.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = 'http://localhost:4000'

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
	return `https://${name}-x8sts.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
	return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === 'object' && 'window' in globalThis

/**
 * Client is an API client for the x8sts Encore application.
 */
export default class Client {
	public readonly appconfig: appconfig.ServiceClient
	public readonly auditlog: auditlog.ServiceClient
	public readonly authn: authn.ServiceClient
	public readonly healthz: healthz.ServiceClient
	public readonly otlp: otlp.ServiceClient
	public readonly usrcategories: usrcategories.ServiceClient
	public readonly usrcourses: usrcourses.ServiceClient
	public readonly usrexport: usrexport.ServiceClient
	public readonly usrgrades: usrgrades.ServiceClient
	public readonly usrreports: usrreports.ServiceClient
	private readonly options: ClientOptions
	private readonly target: string

	/**
	 * @deprecated This constructor is deprecated, and you should move to using BaseURL with an Options object
	 */
	constructor(target: string, token?: string)

	/**
	 * Creates a Client for calling the public and authenticated APIs of your Encore application.
	 *
	 * @param target  The target which the client should be configured to use. See Local and Environment for options.
	 * @param options Options for the client
	 */
	constructor(target: BaseURL, options?: ClientOptions)
	constructor(
		target: string | BaseURL = 'prod',
		options?: string | ClientOptions
	) {
		// Convert the old constructor parameters to a BaseURL object and a ClientOptions object
		if (!target.startsWith('http://') && !target.startsWith('https://')) {
			target = Environment(target)
		}

		if (typeof options === 'string') {
			options = { auth: options }
		}

		this.target = target
		this.options = options ?? {}
		const base = new BaseClient(this.target, this.options)
		this.appconfig = new appconfig.ServiceClient(base)
		this.auditlog = new auditlog.ServiceClient(base)
		this.authn = new authn.ServiceClient(base)
		this.healthz = new healthz.ServiceClient(base)
		this.otlp = new otlp.ServiceClient(base)
		this.usrcategories = new usrcategories.ServiceClient(base)
		this.usrcourses = new usrcourses.ServiceClient(base)
		this.usrexport = new usrexport.ServiceClient(base)
		this.usrgrades = new usrgrades.ServiceClient(base)
		this.usrreports = new usrreports.ServiceClient(base)
	}

	/**
	 * Creates a new Encore client with the given client options set.
	 *
	 * @param options Client options to set. They are merged with existing options.
	 **/
	public with(options: ClientOptions): Client {
		return new Client(this.target, {
			...this.options,
			...options
		})
	}
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
	/**
	 * By default the client will use the inbuilt fetch function for making the API requests.
	 * however you can override it with your own implementation here if you want to run custom
	 * code on each API request made or response received.
	 */
	fetcher?: Fetcher

	/** Default RequestInit to be used for the client */
	requestInit?: Omit<RequestInit, 'headers'> & {
		headers?: Record<string, string>
	}

	/**
	 * Allows you to set the auth token to be used for each request
	 * either by passing in a static token string or by passing in a function
	 * which returns the auth token.
	 *
	 * These tokens will be sent as bearer tokens in the Authorization header.
	 */
	auth?: string | AuthDataGenerator
}

export namespace appconfig {
	/**
	 * LangPackResponse is the shape returned by GET /config/langpack.
	 * Pack is raw JSON so we can support arbitrary nested structures.
	 */
	export interface LangPackResponse {
		pack: JSONValue
	}

	/**
	 * SetLangPackRequest is the body for PUT /config/langpack.
	 */
	export interface SetLangPackRequest {
		pack: JSONValue
	}

	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.DeleteLangPack = this.DeleteLangPack.bind(this)
			this.GetLangPack = this.GetLangPack.bind(this)
			this.SetLangPack = this.SetLangPack.bind(this)
		}

		/**
		 * DeleteLangPack removes the application-level language pack.
		 */
		public async DeleteLangPack(): Promise<void> {
			await this.baseClient.callTypedAPI('DELETE', `/config/langpack`)
		}

		/**
		 * GetLangPack returns the current application-level language pack.
		 * Public so login page can use it.
		 */
		public async GetLangPack(): Promise<LangPackResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/config/langpack`
			)
			return (await resp.json()) as LangPackResponse
		}

		/**
		 * SetLangPack saves a new application-level language pack. Admin only.
		 */
		public async SetLangPack(params: SetLangPackRequest): Promise<void> {
			await this.baseClient.callTypedAPI(
				'PUT',
				`/config/langpack`,
				JSON.stringify(params)
			)
		}
	}
}

export namespace auditlog {
	/**
	 * PurgeRequest specifies the minimum age of logs to delete.
	 */
	export interface PurgeRequest {
		/**
		 * DaysOld deletes entries older than this many days. Minimum: 7.
		 */
		days_old: number
	}

	/**
	 * PurgeResponse reports how many rows were removed.
	 */
	export interface PurgeResponse {
		removed: number
		message: string
	}

	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.GetAuditStats = this.GetAuditStats.bind(this)
			this.ListAuditLogs = this.ListAuditLogs.bind(this)
			this.PurgeAuditLogs = this.PurgeAuditLogs.bind(this)
		}

		/**
		 * GetAuditStats returns aggregate counts for the admin dashboard.
		 * Admin only.
		 */
		public async GetAuditStats(): Promise<audit.StatsResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/audit/stats`
			)
			return (await resp.json()) as audit.StatsResponse
		}

		/**
		 * ListAuditLogs returns a paginated, filterable list of audit log entries.
		 * Supports structured filters and full-text search simultaneously.
		 * Admin only.
		 */
		public async ListAuditLogs(
			params: audit.ListRequest
		): Promise<audit.ListResponse> {
			// Convert our params into the objects we need for the request
			const query = makeRecord<string, string | string[]>({
				actor_id: params['actor_id'].map((v) => String(v)),
				event_type: params['event_type'],
				from: String(params.from),
				limit: String(params.limit),
				outcome: params.outcome,
				page: String(params.page),
				search: params.search,
				to: String(params.to)
			})

			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/audit/logs`,
				undefined,
				{ query }
			)
			return (await resp.json()) as audit.ListResponse
		}

		/**
		 * PurgeAuditLogs deletes audit entries older than DaysOld days.
		 * Admin only.
		 */
		public async PurgeAuditLogs(
			params: PurgeRequest
		): Promise<PurgeResponse> {
			// Convert our params into the objects we need for the request
			const query = makeRecord<string, string | string[]>({
				days_old: String(params['days_old'])
			})

			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'DELETE',
				`/audit/logs`,
				undefined,
				{ query }
			)
			return (await resp.json()) as PurgeResponse
		}
	}
}

export namespace authn {
	export interface OAuth2CallbackRequest {
		state: string
		code: string
	}

	export interface RefreshTokenRequest {
		token: string
	}

	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.Me = this.Me.bind(this)
			this.OAuth2Callback = this.OAuth2Callback.bind(this)
			this.RefreshToken = this.RefreshToken.bind(this)
		}

		/**
		 * GetUserInfo endpoint
		 */
		public async Me(): Promise<entities.UserInfo> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI('GET', `/authn/me`)
			return (await resp.json()) as entities.UserInfo
		}

		/**
		 * Oauth2 callback endpoint
		 */
		public async OAuth2Callback(
			params: OAuth2CallbackRequest
		): Promise<entities.HttpCallbackResponse> {
			// Convert our params into the objects we need for the request
			const query = makeRecord<string, string | string[]>({
				code: params.code,
				state: params.state
			})

			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/oauth2/callback`,
				undefined,
				{ query }
			)

			//Populate the return object from the JSON body and received headers
			const rtn = (await resp.json()) as entities.HttpCallbackResponse
			rtn.Location = mustBeSet(
				'Header `location`',
				resp.headers.get('location')
			)
			return rtn
		}

		/**
		 * RefreshToken endpoint
		 */
		public async RefreshToken(
			params: RefreshTokenRequest
		): Promise<entities.CallbackResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'POST',
				`/authn/refresh`,
				JSON.stringify(params)
			)
			return (await resp.json()) as entities.CallbackResponse
		}
	}
}

export namespace healthz {
	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.HealthCheck = this.HealthCheck.bind(this)
		}

		/**
		 * Healthcheck endpoint
		 */
		public async HealthCheck(): Promise<healthcheck.HealthCheckResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI('GET', `/healthz`)
			return (await resp.json()) as healthcheck.HealthCheckResponse
		}
	}
}

export namespace otlp {
	export interface HealthResponse {
		status: string
		otel_initialized: boolean
	}

	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.Health = this.Health.bind(this)
		}

		/**
		 * Health check endpoint to verify OTEL is initialized
		 */
		public async Health(): Promise<HealthResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/otel/health`
			)
			return (await resp.json()) as HealthResponse
		}
	}
}

export namespace usrcategories {
	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.GetCategories = this.GetCategories.bind(this)
			this.GetCategoryCourses = this.GetCategoryCourses.bind(this)
		}

		/**
		 * GetCategories returns categories appropriate to the caller's role:
		 *   - admin / manager → all visible Moodle categories
		 *   - teacher         → only categories containing courses where they are assigned
		 */
		public async GetCategories(): Promise<entities.GetUsersCategoriesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/categories`
			)
			return (await resp.json()) as entities.GetUsersCategoriesResponse
		}

		/**
		 * GetCategoryCourses returns courses inside a category.
		 * Admin / manager → all courses in the category.
		 * Teacher         → only courses where they are assigned as teacher.
		 */
		public async GetCategoryCourses(
			categoryId: number
		): Promise<entities.GetUsersCoursesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/categories/${encodeURIComponent(categoryId)}/courses`
			)
			return (await resp.json()) as entities.GetUsersCoursesResponse
		}
	}
}

export namespace usrcourses {
	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.GetCourseDetails = this.GetCourseDetails.bind(this)
			this.GetCourses = this.GetCourses.bind(this)
			this.UpdateCourseGrades = this.UpdateCourseGrades.bind(this)
		}

		/**
		 * Get course details endpoint
		 */
		public async GetCourseDetails(
			id: number
		): Promise<mdlapi.GetCourseGradesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/courses/${encodeURIComponent(id)}`
			)
			return (await resp.json()) as mdlapi.GetCourseGradesResponse
		}

		/**
		 * Get courses endpoint
		 */
		public async GetCourses(
			params: entities.GetUsersCoursesRequest
		): Promise<entities.GetUsersCoursesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI('GET', `/courses`)
			return (await resp.json()) as entities.GetUsersCoursesResponse
		}

		/**
		 * Update course grades endpoint
		 */
		public async UpdateCourseGrades(
			params: mdlapi.UpdateGradesRequest
		): Promise<entities.UpdateCourseGradesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'PUT',
				`/courses`,
				JSON.stringify(params)
			)
			return (await resp.json()) as entities.UpdateCourseGradesResponse
		}
	}
}

export namespace usrexport {
	/**
	 * ExportCourseRequest carries the optional template selection.
	 */
	export interface ExportCourseRequest {
		/**
		 * TemplateID is the ID of the template to use.
		 * Pass empty string (or omit the query param) for a default DOCX export.
		 */
		templateId: string
	}

	/**
	 * ExportCourseResponse holds the base64-encoded file ready for browser download.
	 */
	export interface ExportCourseResponse {
		filename: string
		mimetype: string
		/**
		 * Content is the base64-encoded file. Decode with atob() in the browser.
		 */
		content: string
	}

	export interface ExportTemplate {
		id: string
		name: string
		format: string
		size: number
		modified: number
	}

	/**
	 * GetAllTemplatesRequest lets the admin filter by type.
	 */
	export interface GetAllTemplatesRequest {
		/**
		 * Type is one of: course | quiz | assign
		 */
		type: string
	}

	export interface GetTemplatesResponse {
		data: ExportTemplate[]
	}

	/**
	 * UploadExportTemplateRequest carries the base64-encoded template file.
	 */
	export interface UploadExportTemplateRequest {
		/**
		 * Type is one of: course | quiz | assign
		 */
		type: string

		/**
		 * Name is the human-readable label shown in the SMS admin panel.
		 */
		name: string

		/**
		 * Filename is the original filename (extension determines format).
		 */
		filename: string

		/**
		 * Filedata is the base64-encoded file content.
		 */
		filedata: string
	}

	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.DeleteExportTemplate = this.DeleteExportTemplate.bind(this)
			this.ExportCourseGrades = this.ExportCourseGrades.bind(this)
			this.GetAllExportTemplates = this.GetAllExportTemplates.bind(this)
			this.GetCourseExportTemplates =
				this.GetCourseExportTemplates.bind(this)
			this.UploadExportTemplate = this.UploadExportTemplate.bind(this)
		}

		/**
		 * DeleteExportTemplate removes a template by type and ID (admin only).
		 */
		public async DeleteExportTemplate(
			templateType: string,
			templateId: string
		): Promise<void> {
			await this.baseClient.callTypedAPI(
				'DELETE',
				`/admin/export/templates/${encodeURIComponent(templateType)}/${encodeURIComponent(templateId)}`
			)
		}

		/**
		 * ExportCourseGrades generates a grade export and returns the file as base64.
		 */
		public async ExportCourseGrades(
			id: number,
			params: ExportCourseRequest
		): Promise<ExportCourseResponse> {
			// Convert our params into the objects we need for the request
			const query = makeRecord<string, string | string[]>({
				templateId: params.templateId
			})

			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/courses/${encodeURIComponent(id)}/export`,
				undefined,
				{ query }
			)
			return (await resp.json()) as ExportCourseResponse
		}

		/**
		 * GetAllExportTemplates lists all templates for the given type (admin only).
		 */
		public async GetAllExportTemplates(
			params: GetAllTemplatesRequest
		): Promise<GetTemplatesResponse> {
			// Convert our params into the objects we need for the request
			const query = makeRecord<string, string | string[]>({
				type: params.type
			})

			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/admin/export/templates`,
				undefined,
				{ query }
			)
			return (await resp.json()) as GetTemplatesResponse
		}

		/**
		 * GetCourseExportTemplates returns available DOCX/XLSX templates for a course.
		 */
		public async GetCourseExportTemplates(
			id: number
		): Promise<GetTemplatesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/courses/${encodeURIComponent(id)}/export/templates`
			)
			return (await resp.json()) as GetTemplatesResponse
		}

		/**
		 * UploadExportTemplate saves a new template (admin only).
		 */
		public async UploadExportTemplate(
			params: UploadExportTemplateRequest
		): Promise<ExportTemplate> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'POST',
				`/admin/export/templates`,
				JSON.stringify(params)
			)
			return (await resp.json()) as ExportTemplate
		}
	}
}

export namespace usrgrades {
	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.GetUserGrades = this.GetUserGrades.bind(this)
		}

		/**
		 * Get user grades endpoint
		 */
		public async GetUserGrades(): Promise<mdlapi.GetUserGradesResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/users/grades`
			)
			return (await resp.json()) as mdlapi.GetUserGradesResponse
		}
	}
}

/**
 * Package usrreports serves the class results reports: semester and year
 * results of a class for admins and managers, and a student's own result.
 */
export namespace usrreports {
	/**
	 * SaveConductRequest carries rèn luyện scores. An entry without a score
	 * deletes the stored one.
	 */
	export interface SaveConductRequest {
		entries: conduct.Entry[]
	}

	export interface SaveConductResponse {
		saved: number
	}

	export class ServiceClient {
		private baseClient: BaseClient

		constructor(baseClient: BaseClient) {
			this.baseClient = baseClient
			this.GetMyPeriods = this.GetMyPeriods.bind(this)
			this.GetMySemesterResult = this.GetMySemesterResult.bind(this)
			this.GetMyYearResult = this.GetMyYearResult.bind(this)
			this.GetSemesterReport = this.GetSemesterReport.bind(this)
			this.GetYearReport = this.GetYearReport.bind(this)
			this.ListPeriods = this.ListPeriods.bind(this)
			this.SaveConduct = this.SaveConduct.bind(this)
		}

		/**
		 * GetMyPeriods lists the periods of the caller's own class.
		 */
		public async GetMyPeriods(): Promise<classreport.MyPeriodsResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/reports/me/periods`
			)
			return (await resp.json()) as classreport.MyPeriodsResponse
		}

		/**
		 * GetMySemesterResult is the caller's own result and rank for a semester.
		 */
		public async GetMySemesterResult(
			year: number,
			semester: number
		): Promise<classreport.MySemester> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/reports/me/years/${encodeURIComponent(year)}/semesters/${encodeURIComponent(semester)}`
			)
			return (await resp.json()) as classreport.MySemester
		}

		/**
		 * GetMyYearResult is the caller's own result and rank for a year.
		 */
		public async GetMyYearResult(
			year: number
		): Promise<classreport.MyYear> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/reports/me/years/${encodeURIComponent(year)}`
			)
			return (await resp.json()) as classreport.MyYear
		}

		/**
		 * GetSemesterReport is the results of a class for one semester of one year.
		 */
		public async GetSemesterReport(
			categoryId: number,
			year: number,
			semester: number
		): Promise<reporting.SemesterReport> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/reports/classes/${encodeURIComponent(categoryId)}/years/${encodeURIComponent(year)}/semesters/${encodeURIComponent(semester)}`
			)
			return (await resp.json()) as reporting.SemesterReport
		}

		/**
		 * GetYearReport is the results of a class for a whole year.
		 */
		public async GetYearReport(
			categoryId: number,
			year: number
		): Promise<reporting.YearReport> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/reports/classes/${encodeURIComponent(categoryId)}/years/${encodeURIComponent(year)}`
			)
			return (await resp.json()) as reporting.YearReport
		}

		/**
		 * ListPeriods lists the (year, semester) pairs a class has courses in, and the
		 * courses that are in no period because they lack the year or semester field.
		 */
		public async ListPeriods(
			categoryId: number
		): Promise<classreport.PeriodsResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'GET',
				`/reports/classes/${encodeURIComponent(categoryId)}/periods`
			)
			return (await resp.json()) as classreport.PeriodsResponse
		}

		/**
		 * SaveConduct stores rèn luyện scores (0 to 10, one decimal) of a class. All
		 * entries are saved or none.
		 */
		public async SaveConduct(
			categoryId: number,
			params: SaveConductRequest
		): Promise<SaveConductResponse> {
			// Now make the actual call to the API
			const resp = await this.baseClient.callTypedAPI(
				'PUT',
				`/reports/classes/${encodeURIComponent(categoryId)}/conduct`,
				JSON.stringify(params)
			)
			return (await resp.json()) as SaveConductResponse
		}
	}
}

export namespace audit {
	export interface ActorActivity {
		actor_id: number
		actor_role: string
		count: number
	}

	/**
	 * Entry is a single immutable audit log record.
	 */
	export interface Entry {
		id: string
		timestamp: string
		event_type: EventType
		actor_id: number
		actor_role: string
		outcome: Outcome
		service: string
		endpoint: string
		ip_address: string
		details: JSONValue
		error_msg: string
	}

	/**
	 * EventType classifies a significant state-changing or security-relevant
	 * action in the SMS application. Only events in this list are audited —
	 * read-only queries (GET categories, GET courses, etc.) are intentionally
	 * excluded to keep the log meaningful and low-noise.
	 */
	export type EventType = string

	export interface EventTypeCount {
		event_type: EventType
		count: number
	}

	/**
	 * ListRequest is the query shape for GET /audit/logs.
	 * All fields are optional filters; omitting them returns all entries.
	 */
	export interface ListRequest {
		/**
		 * Pagination
		 */
		page: number

		limit: number
		/**
		 * Use a slice so Encore can serialise an absent value as nil.
		 */
		actor_id: number[]

		/**
		 * Use plain strings so Encore doesn't need to know about the custom types.
		 */
		event_type: string

		outcome: string
		from: string
		to: string
		search: string
	}

	export interface ListResponse {
		data: Entry[]
		total: number
		page: number
		limit: number
		total_pages: number
	}

	/**
	 * Outcome describes whether an operation succeeded, failed, or was denied.
	 */
	export type Outcome = string

	export interface StatsResponse {
		total_events: number
		today_events: number
		failure_count: number
		denied_count: number
		top_event_types: EventTypeCount[]
		recent_actors: ActorActivity[]
	}
}

export namespace classreport {
	/**
	 * MyPeriodsResponse lists the periods of the caller's own class. Unlike the
	 * staff listing it has no course names and no unassigned courses.
	 */
	export interface MyPeriodsResponse {
		class: reporting.Class
		periods: Period[]
	}

	/**
	 * MySemester is a student's own semester result. It carries the student's row
	 * and how many students are ranked, never another student's name or score.
	 */
	export interface MySemester {
		class: reporting.Class
		year: number
		semester: number
		totalCredits: number
		courses: reporting.Course[]
		ranked: number
		row: reporting.StudentRow
	}

	/**
	 * MyYear is a student's own year result with each of its semesters.
	 */
	export interface MyYear {
		class: reporting.Class
		year: number
		totalCredits: number
		ranked: number
		row: reporting.YearRow
		periods: MySemester[]
	}

	/**
	 * Period is a (year, semester) pair a class has courses in.
	 */
	export interface Period {
		year: number
		semester: number
		courses: number
	}

	export interface PeriodsResponse {
		class: reporting.Class
		periods: Period[]
		unassigned: UnassignedCourse[]
	}

	/**
	 * UnassignedCourse is a course missing the year or semester field, so it is in
	 * no report.
	 */
	export interface UnassignedCourse {
		id: number
		shortname: string
		missing: string[]
	}
}

export namespace conduct {
	/**
	 * Entry is one requested change. A nil Score deletes the stored score.
	 */
	export interface Entry {
		studentId: number
		year: number
		semester: number
		score: number
	}
}

export namespace entities {
	export interface CallbackResponse {
		accessToken: string
		refreshToken: string
	}

	export interface Category {
		id: number
		name: string
		idnumber: string
		description: string
		parent: number
		visible: boolean
		timemodified: number
	}

	export interface Course {
		id: number
		shortname: string
		fullname: string
		idnumber: string
		visible: number
		summary: string
		category: number
		startdate: number
		enddate: number
		timemodified: number
	}

	export interface GetUsersCategoriesResponse {
		data: Category[]
	}

	export interface GetUsersCoursesRequest {}

	export interface GetUsersCoursesResponse {
		data: Course[]
	}

	export interface HttpCallbackResponse {
		Location: string
	}

	export interface UpdateCourseGradesResponse {
		data: string
	}

	export interface UserInfo {
		id: number
		address: string
		description: string
		email: string
		firstname: string
		idnumber: string
		lang: string
		lastname: string
		phone1: string
		username: string
		role: UserRole
	}

	/**
	 * UserRole is the canonical role for a user in the SMS application.
	 * Priority order (highest to lowest): admin > manager > teacher > student
	 */
	export type UserRole = string
}

export namespace healthcheck {
	export interface HealthCheckResponse {
		message: string
		uptime: number
		timestamp: number
	}
}

export namespace mdlapi {
	export interface CourseMetadata {
		name: string
		value: number
	}

	export type ExamType = number

	export interface GetCourseGradesResponse {
		course: {
			id: number
			fullname: string
			shortname: string
			idnumber: string
			visible: number
			summary: string
			category: number
			startdate: number
			enddate: number
			marker: number
			timemodified: number
		}
		modules: Module[]
		students: Student[]
	}

	export interface GetUserGradesResponse {
		userid: number
		username: string
		firstname: string
		lastname: string
		email: string
		courses: {
			courseid: number
			coursename: string
			shortname: string
			visible: number
			grades: Grade[]
			metadata: CourseMetadata[]
			teachers: Teacher[]
		}[]
	}

	export interface Grade {
		activityid: number
		examtype: ExamType
		grade: number
		iteminstance: number
		itemmodule: string
		itemnumber: number
		moduleid: number
		modulename: string
		/**
		 * Graded is 1 when a grade was entered for the item and 0 when it is
		 * blank. Nil when the plugin predates the field.
		 */
		graded: number
	}

	/**
	 * GradeComponent represents the component parameter for grade_update (format: "mod_{module}")
	 */
	export type GradeComponent = string

	/**
	 * GradeSource represents the source parameter for grade_update (format: "mod/{module}")
	 */
	export type GradeSource = string

	export interface Module {
		id: number
		cmid: number
		name: string
		type: string
		grademin: number
		grademax: number
		examtype: ExamType
		itemnumber: number
	}

	export interface Student {
		id: number
		fullname: string
		username: string
		firstname: string
		lastname: string
		email: string
		/**
		 * IDNumber is the student's Moodle idnumber (Mã HV). Empty when the
		 * plugin predates the field.
		 */
		idnumber: string

		grades: Grade[]
	}

	export interface Teacher {
		id: number
		fullname: string
		email: string
		picture: string
	}

	export interface UpdateGrade {
		studentid: number
		grade: number
	}

	export interface UpdateGradesRequest {
		source: GradeSource
		courseid: number
		component: GradeComponent
		activityid: number
		itemnumber: number
		grades: UpdateGrade[]
	}
}

export namespace reporting {
	/**
	 * Band is a study classification (Điều 11 for a course, Điều 14 for a period).
	 */
	export type Band = string

	/**
	 * Class is a Moodle category.
	 */
	export interface Class {
		id: number
		name: string
		idnumber: string
	}

	/**
	 * Conduct is a rèn luyện score with its label.
	 */
	export interface Conduct {
		score: number
		label: ConductLabel
	}

	/**
	 * ConductLabel is the label of a rèn luyện score. Its thresholds are their own
	 * table, separate from the study bands.
	 */
	export type ConductLabel = string

	/**
	 * Course is a học phần with its credits.
	 */
	export interface Course {
		id: number
		shortname: string
		fullname: string
		credits: number
	}

	/**
	 * CourseStats is the distribution of one course's scores.
	 */
	export interface CourseStats {
		bands: { [key: string]: number }
		mean: number
	}

	/**
	 * SemesterReport is the result of one semester of a class.
	 */
	export interface SemesterReport {
		class: Class
		year: number
		semester: number
		totalCredits: number
		courses: Course[]
		students: StudentRow[]
		summary: Summary
		warnings: Warning[]
	}

	/**
	 * StudentRow is one student of a semester report. Scores is keyed by course id
	 * (as a string, so it is a plain JSON object); a course the student has no
	 * score in is null.
	 */
	export interface StudentRow {
		id: number
		idnumber: string
		fullname: string
		scores: { [key: string]: number }
		gpa: number
		classification: Band
		rank: number
		conduct: Conduct
	}

	/**
	 * Summary is the class-level block under the table.
	 */
	export interface Summary {
		headcount: number
		classGpa: number
		maxGpa: number
		byClassification: { [key: string]: number }
		perCourse: { [key: string]: CourseStats }
		top: TopEntry[]
	}

	/**
	 * TopEntry is a student in the top three ranks (ties can make it longer).
	 */
	export interface TopEntry {
		rank: number
		fullname: string
		gpa: number
	}

	/**
	 * Warning flags a data problem the reader should know about.
	 */
	export interface Warning {
		code: string
		courseId: number
	}

	/**
	 * YearReport is the result of a whole year: every semester plus year totals.
	 */
	export interface YearReport {
		class: Class
		year: number
		totalCredits: number
		periods: SemesterReport[]
		students: YearRow[]
		summary: Summary
		warnings: Warning[]
	}

	/**
	 * YearRow is one student of a year report.
	 */
	export interface YearRow {
		id: number
		idnumber: string
		fullname: string
		gpa: number
		classification: Band
		rank: number
		conduct: Conduct
	}
}

// JSONValue represents an arbitrary JSON value.
export type JSONValue =
	| string
	| number
	| boolean
	| null
	| JSONValue[]
	| { [key: string]: JSONValue }

function encodeQuery(parts: Record<string, string | string[]>): string {
	const pairs: string[] = []
	for (const key in parts) {
		const val = (
			Array.isArray(parts[key]) ? parts[key] : [parts[key]]
		) as string[]
		for (const v of val) {
			pairs.push(`${key}=${encodeURIComponent(v)}`)
		}
	}
	return pairs.join('&')
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(
	record: Record<K, V | undefined>
): Record<K, V> {
	for (const key in record) {
		if (record[key] === undefined) {
			delete record[key]
		}
	}
	return record as Record<K, V>
}

// mustBeSet will throw an APIError with the Data Loss code if value is null or undefined
function mustBeSet<A>(field: string, value: A | null | undefined): A {
	if (value === null || value === undefined) {
		throw new APIError(500, {
			code: ErrCode.DataLoss,
			message: `${field} was unexpectedly ${value}` // ${value} will create the string "null" or "undefined"
		})
	}
	return value
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
	// url safe, no pad
	const base64encoded = btoa(JSON.stringify(headers))
		.replaceAll('=', '')
		.replaceAll('+', '-')
		.replaceAll('/', '_')
	return 'encore.dev.headers.' + base64encoded
}

class WebSocketConnection {
	public ws: WebSocket

	private hasUpdateHandlers: (() => void)[] = []

	constructor(url: string, headers?: Record<string, string>) {
		let protocols = ['encore-ws']
		if (headers) {
			protocols.push(encodeWebSocketHeaders(headers))
		}

		this.ws = new WebSocket(url, protocols)

		this.on('error', () => {
			this.resolveHasUpdateHandlers()
		})

		this.on('close', () => {
			this.resolveHasUpdateHandlers()
		})
	}

	resolveHasUpdateHandlers() {
		const handlers = this.hasUpdateHandlers
		this.hasUpdateHandlers = []

		for (const handler of handlers) {
			handler()
		}
	}

	async hasUpdate() {
		// await until a new message have been received, or the socket is closed
		await new Promise((resolve) => {
			this.hasUpdateHandlers.push(() => resolve(null))
		})
	}

	on(
		type: 'error' | 'close' | 'message' | 'open',
		handler: (event: any) => void
	) {
		this.ws.addEventListener(type, handler)
	}

	off(
		type: 'error' | 'close' | 'message' | 'open',
		handler: (event: any) => void
	) {
		this.ws.removeEventListener(type, handler)
	}

	close() {
		this.ws.close()
	}
}

export class StreamInOut<Request, Response> {
	public socket: WebSocketConnection
	private buffer: Response[] = []

	constructor(url: string, headers?: Record<string, string>) {
		this.socket = new WebSocketConnection(url, headers)
		this.socket.on('message', (event: any) => {
			this.buffer.push(JSON.parse(event.data))
			this.socket.resolveHasUpdateHandlers()
		})
	}

	close() {
		this.socket.close()
	}

	async send(msg: Request) {
		if (this.socket.ws.readyState === WebSocket.CONNECTING) {
			// await that the socket is opened
			await new Promise((resolve) => {
				this.socket.ws.addEventListener('open', resolve, { once: true })
			})
		}

		return this.socket.ws.send(JSON.stringify(msg))
	}

	async next(): Promise<Response | undefined> {
		for await (const next of this) return next
		return undefined
	}

	async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
		while (true) {
			if (this.buffer.length > 0) {
				yield this.buffer.shift() as Response
			} else {
				if (this.socket.ws.readyState === WebSocket.CLOSED) return
				await this.socket.hasUpdate()
			}
		}
	}
}

export class StreamIn<Response> {
	public socket: WebSocketConnection
	private buffer: Response[] = []

	constructor(url: string, headers?: Record<string, string>) {
		this.socket = new WebSocketConnection(url, headers)
		this.socket.on('message', (event: any) => {
			this.buffer.push(JSON.parse(event.data))
			this.socket.resolveHasUpdateHandlers()
		})
	}

	close() {
		this.socket.close()
	}

	async next(): Promise<Response | undefined> {
		for await (const next of this) return next
		return undefined
	}

	async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
		while (true) {
			if (this.buffer.length > 0) {
				yield this.buffer.shift() as Response
			} else {
				if (this.socket.ws.readyState === WebSocket.CLOSED) return
				await this.socket.hasUpdate()
			}
		}
	}
}

export class StreamOut<Request, Response> {
	public socket: WebSocketConnection
	private responseValue: Promise<Response>

	constructor(url: string, headers?: Record<string, string>) {
		let responseResolver: (_: any) => void
		this.responseValue = new Promise(
			(resolve) => (responseResolver = resolve)
		)

		this.socket = new WebSocketConnection(url, headers)
		this.socket.on('message', (event: any) => {
			responseResolver(JSON.parse(event.data))
		})
	}

	async response(): Promise<Response> {
		return this.responseValue
	}

	close() {
		this.socket.close()
	}

	async send(msg: Request) {
		if (this.socket.ws.readyState === WebSocket.CONNECTING) {
			// await that the socket is opened
			await new Promise((resolve) => {
				this.socket.ws.addEventListener('open', resolve, { once: true })
			})
		}

		return this.socket.ws.send(JSON.stringify(msg))
	}
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, 'method' | 'body' | 'headers'> & {
	/** Headers to be sent with the request */
	headers?: Record<string, string>

	/** Query parameters to be sent with the request */
	query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
	| string
	| Promise<string | undefined>
	| undefined

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch

const boundFetch = fetch.bind(this)

class BaseClient {
	readonly baseURL: string
	readonly fetcher: Fetcher
	readonly headers: Record<string, string>
	readonly requestInit: Omit<RequestInit, 'headers'> & {
		headers?: Record<string, string>
	}
	readonly authGenerator?: AuthDataGenerator

	constructor(baseURL: string, options: ClientOptions) {
		this.baseURL = baseURL
		this.headers = {}

		// Add User-Agent header if the script is running in the server
		// because browsers do not allow setting User-Agent headers to requests
		if (!BROWSER) {
			this.headers['User-Agent'] =
				'x8sts-Generated-TS-Client (Encore/v1.58.4)'
		}

		this.requestInit = options.requestInit ?? {}

		// Setup what fetch function we'll be using in the base client
		if (options.fetcher !== undefined) {
			this.fetcher = options.fetcher
		} else {
			this.fetcher = boundFetch
		}

		// Setup an authentication data generator using the auth data token option
		if (options.auth !== undefined) {
			const auth = options.auth
			if (typeof auth === 'function') {
				this.authGenerator = auth
			} else {
				this.authGenerator = () => auth
			}
		}
	}

	async getAuthData(): Promise<CallParameters | undefined> {
		let authData: string | undefined

		// If authorization data generator is present, call it and add the returned data to the request
		if (this.authGenerator) {
			const mayBePromise = this.authGenerator()
			if (mayBePromise instanceof Promise) {
				authData = await mayBePromise
			} else {
				authData = mayBePromise
			}
		}

		if (authData) {
			const data: CallParameters = {}

			data.headers = {}
			data.headers['Authorization'] = 'Bearer ' + authData

			return data
		}

		return undefined
	}

	// createStreamInOut sets up a stream to a streaming API endpoint.
	async createStreamInOut<Request, Response>(
		path: string,
		params?: CallParameters
	): Promise<StreamInOut<Request, Response>> {
		let { query, headers } = params ?? {}

		// Fetch auth data if there is any
		const authData = await this.getAuthData()

		// If we now have authentication data, add it to the request
		if (authData) {
			if (authData.query) {
				query = { ...query, ...authData.query }
			}
			if (authData.headers) {
				headers = { ...headers, ...authData.headers }
			}
		}

		const queryString = query ? '?' + encodeQuery(query) : ''
		return new StreamInOut(this.baseURL + path + queryString, headers)
	}

	// createStreamIn sets up a stream to a streaming API endpoint.
	async createStreamIn<Response>(
		path: string,
		params?: CallParameters
	): Promise<StreamIn<Response>> {
		let { query, headers } = params ?? {}

		// Fetch auth data if there is any
		const authData = await this.getAuthData()

		// If we now have authentication data, add it to the request
		if (authData) {
			if (authData.query) {
				query = { ...query, ...authData.query }
			}
			if (authData.headers) {
				headers = { ...headers, ...authData.headers }
			}
		}

		const queryString = query ? '?' + encodeQuery(query) : ''
		return new StreamIn(this.baseURL + path + queryString, headers)
	}

	// createStreamOut sets up a stream to a streaming API endpoint.
	async createStreamOut<Request, Response>(
		path: string,
		params?: CallParameters
	): Promise<StreamOut<Request, Response>> {
		let { query, headers } = params ?? {}

		// Fetch auth data if there is any
		const authData = await this.getAuthData()

		// If we now have authentication data, add it to the request
		if (authData) {
			if (authData.query) {
				query = { ...query, ...authData.query }
			}
			if (authData.headers) {
				headers = { ...headers, ...authData.headers }
			}
		}

		const queryString = query ? '?' + encodeQuery(query) : ''
		return new StreamOut(this.baseURL + path + queryString, headers)
	}

	// callTypedAPI makes an API call, defaulting content type to "application/json"
	public async callTypedAPI(
		method: string,
		path: string,
		body?: RequestInit['body'],
		params?: CallParameters
	): Promise<Response> {
		return this.callAPI(method, path, body, {
			...params,
			headers: { 'Content-Type': 'application/json', ...params?.headers }
		})
	}

	// callAPI is used by each generated API method to actually make the request
	public async callAPI(
		method: string,
		path: string,
		body?: RequestInit['body'],
		params?: CallParameters
	): Promise<Response> {
		let { query, headers, ...rest } = params ?? {}
		const init = {
			...this.requestInit,
			...rest,
			method,
			body: body ?? null
		}

		// Merge our headers with any predefined headers
		init.headers = { ...this.headers, ...init.headers, ...headers }

		// Fetch auth data if there is any
		const authData = await this.getAuthData()

		// If we now have authentication data, add it to the request
		if (authData) {
			if (authData.query) {
				query = { ...query, ...authData.query }
			}
			if (authData.headers) {
				init.headers = { ...init.headers, ...authData.headers }
			}
		}

		// Make the actual request
		const queryString = query ? '?' + encodeQuery(query) : ''
		const response = await this.fetcher(
			this.baseURL + path + queryString,
			init
		)

		// handle any error responses
		if (!response.ok) {
			// try and get the error message from the response body
			let body: APIErrorResponse = {
				code: ErrCode.Unknown,
				message: `request failed: status ${response.status}`
			}

			// if we can get the structured error we should, otherwise give a best effort
			try {
				const text = await response.text()

				try {
					const jsonBody = JSON.parse(text)
					if (isAPIErrorResponse(jsonBody)) {
						body = jsonBody
					} else {
						body.message += ': ' + JSON.stringify(jsonBody)
					}
				} catch {
					body.message += ': ' + text
				}
			} catch (e) {
				// otherwise we just append the text to the error message
				body.message += ': ' + String(e)
			}

			throw new APIError(response.status, body)
		}

		return response
	}
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
	code: ErrCode
	message: string
	details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
	return (
		err !== undefined &&
		err !== null &&
		isErrCode(err.code) &&
		typeof err.message === 'string' &&
		(err.details === undefined ||
			err.details === null ||
			typeof err.details === 'object')
	)
}

function isErrCode(code: any): code is ErrCode {
	return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
	/**
	 * The HTTP status code associated with the error.
	 */
	public readonly status: number

	/**
	 * The Encore error code
	 */
	public readonly code: ErrCode

	/**
	 * The error details
	 */
	public readonly details?: any

	constructor(status: number, response: APIErrorResponse) {
		// extending errors causes issues after you construct them, unless you apply the following fixes
		super(response.message)

		// set error name as constructor name, make it not enumerable to keep native Error behavior
		// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
		Object.defineProperty(this, 'name', {
			value: 'APIError',
			enumerable: false,
			configurable: true
		})

		// fix the prototype chain
		if ((Object as any).setPrototypeOf == undefined) {
			;(this as any).__proto__ = APIError.prototype
		} else {
			Object.setPrototypeOf(this, APIError.prototype)
		}

		// capture a stack trace
		if ((Error as any).captureStackTrace !== undefined) {
			;(Error as any).captureStackTrace(this, this.constructor)
		}

		this.status = status
		this.code = response.code
		this.details = response.details
	}
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
	return err instanceof APIError
}

export enum ErrCode {
	/**
	 * OK indicates the operation was successful.
	 */
	OK = 'ok',

	/**
	 * Canceled indicates the operation was canceled (typically by the caller).
	 *
	 * Encore will generate this error code when cancellation is requested.
	 */
	Canceled = 'canceled',

	/**
	 * Unknown error. An example of where this error may be returned is
	 * if a Status value received from another address space belongs to
	 * an error-space that is not known in this address space. Also
	 * errors raised by APIs that do not return enough error information
	 * may be converted to this error.
	 *
	 * Encore will generate this error code in the above two mentioned cases.
	 */
	Unknown = 'unknown',

	/**
	 * InvalidArgument indicates client specified an invalid argument.
	 * Note that this differs from FailedPrecondition. It indicates arguments
	 * that are problematic regardless of the state of the system
	 * (e.g., a malformed file name).
	 *
	 * This error code will not be generated by the gRPC framework.
	 */
	InvalidArgument = 'invalid_argument',

	/**
	 * DeadlineExceeded means operation expired before completion.
	 * For operations that change the state of the system, this error may be
	 * returned even if the operation has completed successfully. For
	 * example, a successful response from a server could have been delayed
	 * long enough for the deadline to expire.
	 *
	 * The gRPC framework will generate this error code when the deadline is
	 * exceeded.
	 */
	DeadlineExceeded = 'deadline_exceeded',

	/**
	 * NotFound means some requested entity (e.g., file or directory) was
	 * not found.
	 *
	 * This error code will not be generated by the gRPC framework.
	 */
	NotFound = 'not_found',

	/**
	 * AlreadyExists means an attempt to create an entity failed because one
	 * already exists.
	 *
	 * This error code will not be generated by the gRPC framework.
	 */
	AlreadyExists = 'already_exists',

	/**
	 * PermissionDenied indicates the caller does not have permission to
	 * execute the specified operation. It must not be used for rejections
	 * caused by exhausting some resource (use ResourceExhausted
	 * instead for those errors). It must not be
	 * used if the caller cannot be identified (use Unauthenticated
	 * instead for those errors).
	 *
	 * This error code will not be generated by the gRPC core framework,
	 * but expect authentication middleware to use it.
	 */
	PermissionDenied = 'permission_denied',

	/**
	 * ResourceExhausted indicates some resource has been exhausted, perhaps
	 * a per-user quota, or perhaps the entire file system is out of space.
	 *
	 * This error code will be generated by the gRPC framework in
	 * out-of-memory and server overload situations, or when a message is
	 * larger than the configured maximum size.
	 */
	ResourceExhausted = 'resource_exhausted',

	/**
	 * FailedPrecondition indicates operation was rejected because the
	 * system is not in a state required for the operation's execution.
	 * For example, directory to be deleted may be non-empty, an rmdir
	 * operation is applied to a non-directory, etc.
	 *
	 * A litmus test that may help a service implementor in deciding
	 * between FailedPrecondition, Aborted, and Unavailable:
	 *  (a) Use Unavailable if the client can retry just the failing call.
	 *  (b) Use Aborted if the client should retry at a higher-level
	 *      (e.g., restarting a read-modify-write sequence).
	 *  (c) Use FailedPrecondition if the client should not retry until
	 *      the system state has been explicitly fixed. E.g., if an "rmdir"
	 *      fails because the directory is non-empty, FailedPrecondition
	 *      should be returned since the client should not retry unless
	 *      they have first fixed up the directory by deleting files from it.
	 *  (d) Use FailedPrecondition if the client performs conditional
	 *      REST Get/Update/Delete on a resource and the resource on the
	 *      server does not match the condition. E.g., conflicting
	 *      read-modify-write on the same resource.
	 *
	 * This error code will not be generated by the gRPC framework.
	 */
	FailedPrecondition = 'failed_precondition',

	/**
	 * Aborted indicates the operation was aborted, typically due to a
	 * concurrency issue like sequencer check failures, transaction aborts,
	 * etc.
	 *
	 * See litmus test above for deciding between FailedPrecondition,
	 * Aborted, and Unavailable.
	 */
	Aborted = 'aborted',

	/**
	 * OutOfRange means operation was attempted past the valid range.
	 * E.g., seeking or reading past end of file.
	 *
	 * Unlike InvalidArgument, this error indicates a problem that may
	 * be fixed if the system state changes. For example, a 32-bit file
	 * system will generate InvalidArgument if asked to read at an
	 * offset that is not in the range [0,2^32-1], but it will generate
	 * OutOfRange if asked to read from an offset past the current
	 * file size.
	 *
	 * There is a fair bit of overlap between FailedPrecondition and
	 * OutOfRange. We recommend using OutOfRange (the more specific
	 * error) when it applies so that callers who are iterating through
	 * a space can easily look for an OutOfRange error to detect when
	 * they are done.
	 *
	 * This error code will not be generated by the gRPC framework.
	 */
	OutOfRange = 'out_of_range',

	/**
	 * Unimplemented indicates operation is not implemented or not
	 * supported/enabled in this service.
	 *
	 * This error code will be generated by the gRPC framework. Most
	 * commonly, you will see this error code when a method implementation
	 * is missing on the server. It can also be generated for unknown
	 * compression algorithms or a disagreement as to whether an RPC should
	 * be streaming.
	 */
	Unimplemented = 'unimplemented',

	/**
	 * Internal errors. Means some invariants expected by underlying
	 * system has been broken. If you see one of these errors,
	 * something is very broken.
	 *
	 * This error code will be generated by the gRPC framework in several
	 * internal error conditions.
	 */
	Internal = 'internal',

	/**
	 * Unavailable indicates the service is currently unavailable.
	 * This is a most likely a transient condition and may be corrected
	 * by retrying with a backoff. Note that it is not always safe to retry
	 * non-idempotent operations.
	 *
	 * See litmus test above for deciding between FailedPrecondition,
	 * Aborted, and Unavailable.
	 *
	 * This error code will be generated by the gRPC framework during
	 * abrupt shutdown of a server process or network connection.
	 */
	Unavailable = 'unavailable',

	/**
	 * DataLoss indicates unrecoverable data loss or corruption.
	 *
	 * This error code will not be generated by the gRPC framework.
	 */
	DataLoss = 'data_loss',

	/**
	 * Unauthenticated indicates the request does not have valid
	 * authentication credentials for the operation.
	 *
	 * The gRPC framework will generate this error code when the
	 * authentication metadata is invalid or a Credentials callback fails,
	 * but also expect authentication middleware to generate it.
	 */
	Unauthenticated = 'unauthenticated'
}
