CREATE TABLE IF NOT EXISTS `students` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` text DEFAULT CURRENT_TIMESTAMP,
	`fullName` text DEFAULT '',
	`birthPlace` text DEFAULT '',
	`address` text DEFAULT '',
	`dob` text DEFAULT '',
	`rank` text DEFAULT '',
	`previousUnit` text DEFAULT '',
	`previousPosition` text DEFAULT '',
	`position` text DEFAULT 'Chiến sĩ',
	`ethnic` text DEFAULT '',
	`religion` text DEFAULT 'Không',
	`enlistmentPeriod` text DEFAULT '',
	`politicalOrg` text NOT NULL,
	`politicalOrgOfficialDate` text DEFAULT '',
	`cpvId` text,
	`educationLevel` text DEFAULT '',
	`schoolName` text DEFAULT '',
	`major` text DEFAULT '',
	`isGraduated` integer DEFAULT false,
	`talent` text DEFAULT 'Không',
	`shortcoming` text DEFAULT 'Không',
	`policyBeneficiaryGroup` text DEFAULT 'Không',
	`fatherName` text DEFAULT '',
	`fatherDob` text DEFAULT '',
	`fatherPhoneNumber` text DEFAULT '',
	`fatherJob` text DEFAULT '',
	`motherName` text DEFAULT '',
	`motherDob` text DEFAULT '',
	`motherPhoneNumber` text DEFAULT '',
	`motherJob` text DEFAULT '',
	`isMarried` integer DEFAULT false,
	`spouseName` text DEFAULT '',
	`spouseDob` text DEFAULT '',
	`spouseJob` text DEFAULT '',
	`spousePhoneNumber` text DEFAULT '',
	`childrenInfos` text DEFAULT '[]',
	`familySize` integer,
	`familyBackground` text DEFAULT 'Không',
	`familyBirthOrder` text DEFAULT '',
	`achievement` text DEFAULT 'Không',
	`disciplinaryHistory` text DEFAULT 'Không',
	`phone` text DEFAULT '',
	`classId` integer,
	`unitId` integer,
	`cpvOfficialAt` text,
	`avatar` text,
	`siblings` text DEFAULT '[]',
	`contactPerson` text DEFAULT '{}',
	`studentId` text,
	`relatedDocumentations` text,
	`status` text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `students_classId_idx` ON `students` (`classId`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `students_unitId_idx` ON `students` (`unitId`);
